# -*- coding: utf-8 -*-
"""internetsp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SvjrYwZDm0udL1Bwu3iMVSa4MVfXOFCl
"""

import pandas as pd
import numpy as np

from shapely import wkt

import folium
from folium.plugins import MarkerCluster

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score

df = pd.read_csv('sample.csv')
df.head()

# Convert kbps → Mbps
df['avg_d_mbps'] = df['avg_d_kbps'] / 1000
df['avg_u_mbps'] = df['avg_u_kbps'] / 1000

# Remove unreliable tiles
df = df[df['tests'] >= 3]

# Create target variable (Internet Quality Score)
df['quality_score'] = (
    df['avg_d_mbps'] * 0.6 +
    df['avg_u_mbps'] * 0.3 -
    df['avg_lat_ms'] * 0.01
)

df['geometry'] = df['tile'].apply(wkt.loads)
df['lat'] = df['geometry'].apply(lambda g: g.centroid.y)
df['lon'] = df['geometry'].apply(lambda g: g.centroid.x)

features = [
    'avg_d_mbps',
    'avg_u_mbps',
    'avg_lat_ms',
    'tests',
    'devices'
]

target = 'quality_score'

X = df[features]
y = df[target]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = RandomForestRegressor(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("MAE:", mean_absolute_error(y_test, y_pred))
print("R² :", r2_score(y_test, y_pred))

df['predicted_quality'] = model.predict(df[features])

top_tiles = (
    df
    .groupby('quadkey')['predicted_quality']
    .mean()
    .sort_values(ascending=False)
)

top_tiles.head(10)

# Create base map centered on data
m = folium.Map(
    location=[df['lat'].mean(), df['lon'].mean()],
    zoom_start=5,
    tiles='cartodbpositron'
)

cluster = MarkerCluster().add_to(m)

for _, row in df.iterrows():

    score = row['predicted_quality']

    if score >= 30:
        color = 'green'
    elif score >= 15:
        color = 'orange'
    else:
        color = 'red'

    folium.CircleMarker(
        location=[row['lat'], row['lon']],
        radius=5,
        color=color,
        fill=True,
        fill_opacity=0.7,
        popup=(
            f"<b>Internet Quality</b><br>"
            f"Score: {score:.2f}<br>"
            f"Download: {row['avg_d_mbps']:.2f} Mbps<br>"
            f"Upload: {row['avg_u_mbps']:.2f} Mbps<br>"
            f"Latency: {row['avg_lat_ms']} ms<br>"
            f"Tests: {row['tests']}"
        )
    ).add_to(cluster)

m

m.save("internet_quality_map.html")

df[['lat', 'lon', 'predicted_quality',
    'avg_d_mbps', 'avg_u_mbps', 'avg_lat_ms']].to_csv(
    'internet_quality_map_data.csv',
    index=False
)